# -*- restclient -*-
:client_id = 5beus1JLVqz6N4aZ6AxVwZlQMpuL53cf
:verifier = MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE
:challenge = huVe5Sif9SgWtYkAgGw7CvEPQ6NI0AdBuSVp1DNWPLI

#
GET https://bismi.aidbox.io/fhir/Patient

#
POST https://bismi.aidbox.io/fhir/Patient
Content-Type: application/json
{"name": [{"use": "official", "given": ["anna"]}],
 "birthDate": "2017-4-28",
 "resourceType": "Patient",
 "active": true,
 "telecom": [{"use": "mobile", "rank": 1, "value": "123", "system": "phone"}],
 "gender": "female"}

#
DELETE https://bismi.aidbox.io/fhir/Patient/

#
# AUTH0
#
#
GET https://bismi.eu.auth0.com/authorize?response_type=code&client_id=:client_id&code_challenge=:challenge&code_challenge_method=S256&redirect_uri=http://bismi.ru/callback
#audience=API_IDENTIFIER&
#scope=SCOPE&

#
POST https://bismi.eu.auth0.com/oauth/token
Content-Type: application/json

{
"grant_type": "authorization_code",
"client_id": ":client_id",
"code": "_ZaN2xgLNxQKhxFJ",
"code_verifier": ":verifier",
"redirect_uri": "http://bismi.ru/callback"
}